# Generated by Django 3.1.5 on 2021-06-03 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FoursquareVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(blank=True, null=True)),
                ('place_id', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IgLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=50)),
                ('permalink', models.URLField(max_length=1000)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdtime', models.CharField(blank=True, max_length=1000, null=True)),
                ('ig_id', models.CharField(blank=True, max_length=1000)),
                ('categories', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('foursquare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.foursquarevenue')),
                ('google_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.googleplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boi', models.TextField(blank=True, default='no bio...', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=1000, null=True, upload_to='postimage/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='ALLPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=1000)),
                ('post_url', models.URLField(max_length=1000)),
                ('message', models.URLField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('fb_permalink', models.URLField(max_length=1000)),
                ('ig_permalink', models.URLField(max_length=1000)),
                ('image', models.ImageField(blank=1000, null=True, upload_to='allposts/')),
                ('google_info', models.JSONField(blank=True, null=True)),
                ('place_id', models.CharField(max_length=1000)),
                ('location_id', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('ig_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('ig_id', models.CharField(blank=True, max_length=30, null=True)),
                ('line_user_id', models.CharField(max_length=100, null=True)),
                ('profile_picture', models.URLField(blank=True, max_length=1000)),
                ('inviter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
