# Generated by Django 3.1.5 on 2021-06-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApiSetting',
        ),
        migrations.RemoveField(
            model_name='account',
            name='line_user_id',
        ),
        migrations.DeleteModel(
            name='ALLPost',
        ),
    ]
