# Generated by Django 3.1.5 on 2021-03-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210312_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpost',
            name='google_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
