# Generated by Django 3.1.5 on 2021-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210510_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city_state',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
