# Generated by Django 3.1.5 on 2021-02-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_info',
        ),
    ]
