# Generated by Django 3.1.5 on 2021-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_account_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fb_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ig_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
