# Generated by Django 3.1.5 on 2021-05-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210517_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoursquareVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='foursquare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.foursquarevenue'),
        ),
    ]
