# Generated by Django 3.1.5 on 2021-03-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210315_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='location_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
