# Generated by Django 3.1.5 on 2021-03-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_igpost_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='line_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
