# Generated by Django 3.1.5 on 2021-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='postkit_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
