# Generated by Django 3.1.5 on 2021-02-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210224_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fb_token',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ig_token',
        ),
    ]
