# Generated by Django 3.1.5 on 2021-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_account_postkit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=1000, null=True, upload_to='profileimage/'),
        ),
    ]
