# Generated by Django 3.1.5 on 2021-03-17 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20210317_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=1000)),
                ('post_url', models.URLField(max_length=1000)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('permalink', models.URLField(max_length=1000)),
                ('image', models.ImageField(blank=1000, null=True, upload_to='allposts/')),
                ('google_info', models.JSONField(blank=True, null=True)),
                ('place_id', models.CharField(max_length=1000)),
                ('location_id', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='igpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='FbPost',
        ),
        migrations.DeleteModel(
            name='IgPost',
        ),
    ]
