# Generated by Django 3.1.5 on 2021-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210317_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='message',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
