# Generated by Django 3.1.5 on 2021-07-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_account_postkit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='postkit_url',
            field=models.ImageField(blank=True, null=True, upload_to='profileImage/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postimage/'),
        ),
    ]
