# Generated by Django 3.1.5 on 2021-02-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210224_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='post_url',
        ),
    ]
