# Generated by Django 3.1.5 on 2021-03-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_allpost_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allpost',
            old_name='permalink',
            new_name='fb_permalink',
        ),
        migrations.AddField(
            model_name='allpost',
            name='ig_permalink',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
