# Generated by Django 3.1.5 on 2021-07-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
