# Generated by Django 3.1.5 on 2021-03-17 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20210317_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(blank=True, null=True)),
                ('place_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IgLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=50)),
                ('permalink', models.URLField(max_length=1000)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('ig_id', models.CharField(max_length=1000)),
                ('google_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.googleplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=1000, null=True, upload_to='postimage/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
    ]
