# Generated by Django 3.1.5 on 2021-02-24 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20210224_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='FbPost',
        ),
    ]
