# Generated by Django 3.1.5 on 2021-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_googleplace_iglocation_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplace',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleplace',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
