# Generated by Django 3.1.5 on 2021-07-20 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20210716_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_friends',
            field=models.ManyToManyField(blank=True, related_name='fb_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
