# Generated by Django 3.1.5 on 2021-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210317_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
            
        ),
    ]
