# Generated by Django 3.1.5 on 2021-03-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_igpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='permalink',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
