# Generated by Django 3.1.5 on 2021-03-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_igpost_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='place_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
