# Generated by Django 3.1.5 on 2021-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210720_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fb_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ig_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
