# Generated by Django 3.1.5 on 2021-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210305_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='line_use_id',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
