# Generated by Django 3.1.5 on 2021-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210320_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='follow_line_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
