# Generated by Django 3.1.5 on 2021-03-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210308_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='line_user_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
