# Generated by Django 3.1.5 on 2021-04-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210322_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
