# Generated by Django 3.1.5 on 2021-03-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210310_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediapost',
            old_name='Image_name',
            new_name='image_name',
        ),
    ]
