# Generated by Django 3.1.6 on 2021-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210403_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
