# Generated by Django 3.1.5 on 2021-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210310_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
