# Generated by Django 3.1.5 on 2021-04-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplace',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
