# Generated by Django 3.1.5 on 2021-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mediapost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medias'),
        ),
        migrations.DeleteModel(
            name='MediaPost',
        ),
    ]
