# Generated by Django 3.1.5 on 2021-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210311_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='line_user_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
