# Generated by Django 3.1.5 on 2021-05-06 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210430_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplace',
            name='city_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='ig_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
